const db = require('../models')
function run() {
  db.Product.findAll().then(products => {
    if (products.length === 0) {
      const arrProduct = [
        {
          o_variant: '350 XLT Van',
          variant: 'XLT',
          year: '2019',
          primary_image: 'https://i.ibb.co/9ZYqg1L/ford-transit-expert.png',
          thumbnail1: 'https://i.ibb.co/9ZYqg1L/ford-transit-expert.png',
          thumbnail2: 'https://i.ibb.co/9ZYqg1L/ford-transit-expert.png',
          thumbnail3: 'https://i.ibb.co/9ZYqg1L/ford-transit-expert.png',
          thumbnail4: 'https://i.ibb.co/9ZYqg1L/ford-transit-expert.png',
          short_description: 'Lorem Ipsum',
          long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          acquisition_cost: 285000,
          scrap_value: [12000, 20000],
          leasing_period: [12, 24],
          start_kilometer: 10000,
          end_kilometer: 35000,
          interval_kilometer: 5000,
          interval_price: 2500,
          model: 1,
          size: 1,
          colors: [1, 2],
          categories: [1],
          professions: [1, 2],
          equipments: [1, 2],
          economy: 25,
          gear: 'manual',
          energyLabel: 5,
          status: 'COMPLETED'
        },
        {
          o_variant: '2.5 SL 4D Sedan',
          variant: 'SL',
          year: '2018',
          primary_image: 'https://i.ibb.co/zPGBxDY/altima-2-5-sv-4d-sedan.png',
          thumbnail1: 'https://i.ibb.co/zPGBxDY/altima-2-5-sv-4d-sedan.png',
          thumbnail2: 'https://i.ibb.co/zPGBxDY/altima-2-5-sv-4d-sedan.png',
          thumbnail3: 'https://i.ibb.co/zPGBxDY/altima-2-5-sv-4d-sedan.png',
          thumbnail4: 'https://i.ibb.co/zPGBxDY/altima-2-5-sv-4d-sedan.png',
          short_description: 'Lorem Ipsum',
          long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          acquisition_cost: 185000,
          scrap_value: [20000, 30000],
          leasing_period: [24, 48],
          start_kilometer: 15000,
          end_kilometer: 30000,
          interval_kilometer: 5000,
          interval_price: 2500,
          model: 2,
          size: 1,
          colors: [1, 2],
          categories: [1],
          professions: [1, 2],
          equipments: [1, 2],
          economy: 30,
          gear: 'manual',
          energyLabel: 8,
          status: 'COMPLETED'
        },
        {
          o_variant: 'B5-O',
          variant: 'B5-O',
          year: '2019',
          primary_image: 'https://i.ibb.co/ZJsQHYt/e960ef8798cbeb302f51edaa4be09c7a.png',
          thumbnail1: 'https://i.ibb.co/ZJsQHYt/e960ef8798cbeb302f51edaa4be09c7a.png',
          thumbnail2: 'https://i.ibb.co/ZJsQHYt/e960ef8798cbeb302f51edaa4be09c7a.png',
          thumbnail3: 'https://i.ibb.co/ZJsQHYt/e960ef8798cbeb302f51edaa4be09c7a.png',
          thumbnail4: 'https://i.ibb.co/ZJsQHYt/e960ef8798cbeb302f51edaa4be09c7a.png',
          short_description: 'Lorem Ipsum',
          long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          acquisition_cost: 205000,
          scrap_value: [20000, 30000],
          leasing_period: [24, 48],
          start_kilometer: 30000,
          end_kilometer: 45000,
          interval_kilometer: 5000,
          interval_price: 2500,
          model: 2,
          size: 1,
          colors: [1, 2],
          categories: [1],
          professions: [1, 2],
          equipments: [1, 2],
          economy: 20,
          gear: 'manual',
          energyLabel: 5,
          status: 'COMPLETED'
        },
        {
          o_variant: '2.5 SV 4DR',
          variant: 'SV',
          year: '2019',
          primary_image: 'https://i.ibb.co/HdJHkyV/nissan-altima-2-5s-4dr.png',
          thumbnail1: 'https://i.ibb.co/HdJHkyV/nissan-altima-2-5s-4dr.png',
          thumbnail2: 'https://i.ibb.co/HdJHkyV/nissan-altima-2-5s-4dr.png',
          thumbnail3: 'https://i.ibb.co/HdJHkyV/nissan-altima-2-5s-4dr.png',
          thumbnail4: 'https://i.ibb.co/HdJHkyV/nissan-altima-2-5s-4dr.png',
          short_description: 'Lorem Ipsum',
          long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          acquisition_cost: 285000,
          scrap_value: [30000, 50000],
          leasing_period: [36, 48],
          start_kilometer: 30000,
          end_kilometer: 55000,
          interval_kilometer: 5000,
          interval_price: 2500,
          model: 2,
          size: 1,
          colors: [1, 2],
          categories: [1],
          professions: [1, 2],
          equipments: [1, 2],
          economy: 40,
          gear: 'manual',
          energyLabel: 9,
          status: 'COMPLETED'
        },
        {
          o_variant: 'Expert',
          variant: 'Expert',
          year: '2019',
          primary_image: 'https://i.ibb.co/Nrw5vXg/8095-2017-nissan-rogue-sport.png',
          thumbnail1: 'https://i.ibb.co/Nrw5vXg/8095-2017-nissan-rogue-sport.png',
          thumbnail2: 'https://i.ibb.co/Nrw5vXg/8095-2017-nissan-rogue-sport.png',
          thumbnail3: 'https://i.ibb.co/Nrw5vXg/8095-2017-nissan-rogue-sport.png',
          thumbnail4: 'https://i.ibb.co/Nrw5vXg/8095-2017-nissan-rogue-sport.png',
          short_description: 'Lorem Ipsum',
          long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          acquisition_cost: 385000,
          scrap_value: [10000, 34000],
          leasing_period: [12, 36],
          start_kilometer: 10000,
          end_kilometer: 30000,
          interval_kilometer: 3000,
          interval_price: 2500,
          model: 3,
          size: 1,
          colors: [1, 2],
          categories: [1],
          professions: [1, 2],
          equipments: [1, 2],
          economy: 25,
          gear: 'manual',
          energyLabel: 8,
          status: 'COMPLETED'
        },
        {
          o_variant: 'SV Duluth MW',
          variant: 'SV',
          year: '2019',
          primary_image: 'https://i.ibb.co/9rfpn4L/sv-duluth.png',
          thumbnail1: 'https://i.ibb.co/9rfpn4L/sv-duluth.png',
          thumbnail2: 'https://i.ibb.co/9rfpn4L/sv-duluth.png',
          thumbnail3: 'https://i.ibb.co/9rfpn4L/sv-duluth.png',
          thumbnail4: 'https://i.ibb.co/9rfpn4L/sv-duluth.png',
          short_description: 'Lorem Ipsum',
          long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          acquisition_cost: 385000,
          scrap_value: [20000, 30000],
          leasing_period: [24, 36],
          start_kilometer: 20000,
          end_kilometer: 45000,
          interval_kilometer: 5000,
          interval_price: 2500,
          model: 3,
          size: 1,
          colors: [1, 2],
          categories: [1],
          professions: [1, 2],
          equipments: [1, 2],
          economy: 30,
          gear: 'manual',
          energyLabel: 5,
          status: 'COMPLETED'
        },
        {
          o_variant: 'S 4D Crew Cab',
          variant: 'S',
          year: '2018',
          primary_image: 'https://i.ibb.co/XzGVr7k/nissan-titan-s-4d-crew-cab.png',
          thumbnail1: 'https://i.ibb.co/XzGVr7k/nissan-titan-s-4d-crew-cab.png',
          thumbnail2: 'https://i.ibb.co/XzGVr7k/nissan-titan-s-4d-crew-cab.png',
          thumbnail3: 'https://i.ibb.co/XzGVr7k/nissan-titan-s-4d-crew-cab.png',
          thumbnail4: 'https://i.ibb.co/XzGVr7k/nissan-titan-s-4d-crew-cab.png',
          short_description: 'Lorem Ipsum',
          long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          acquisition_cost: 385000,
          scrap_value: [40000, 60000],
          leasing_period: [12, 24],
          start_kilometer: 10000,
          end_kilometer: 35000,
          interval_kilometer: 5000,
          interval_price: 2500,
          model: 4,
          size: 1,
          colors: [1, 2],
          categories: [1],
          professions: [1, 2],
          equipments: [1, 2],
          economy: 25,
          gear: 'manual',
          energyLabel: 10,
          status: 'COMPLETED'
        },
        {
          o_variant: 'xDrive40i',
          variant: 'xDrive40i',
          year: '2019',
          primary_image: 'https://i.ibb.co/9NmFqJH/bmw-x7-xdrive40i.png',
          thumbnail1: 'https://i.ibb.co/9NmFqJH/bmw-x7-xdrive40i.png',
          thumbnail2: 'https://i.ibb.co/9NmFqJH/bmw-x7-xdrive40i.png',
          thumbnail3: 'https://i.ibb.co/9NmFqJH/bmw-x7-xdrive40i.png',
          thumbnail4: 'https://i.ibb.co/9NmFqJH/bmw-x7-xdrive40i.png',
          short_description: 'Lorem Ipsum',
          long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          acquisition_cost: 185000,
          scrap_value: [10000, 20000],
          leasing_period: [12, 24],
          start_kilometer: 15000,
          end_kilometer: 35000,
          interval_kilometer: 5000,
          interval_price: 2500,
          model: 5,
          size: 2,
          colors: [1, 2],
          categories: [1],
          professions: [1, 2],
          equipments: [1, 2],
          economy: 25,
          gear: 'manual',
          energyLabel: 6,
          status: 'COMPLETED'
        },
        {
          o_variant: 'Expert',
          variant: 'Expert',
          year: '2019',
          primary_image: 'https://i.ibb.co/NCYrfQv/ford-ecosport-expert.png',
          thumbnail1: 'https://i.ibb.co/NCYrfQv/ford-ecosport-expert.png',
          thumbnail2: 'https://i.ibb.co/NCYrfQv/ford-ecosport-expert.png',
          thumbnail3: 'https://i.ibb.co/NCYrfQv/ford-ecosport-expert.png',
          thumbnail4: 'https://i.ibb.co/NCYrfQv/ford-ecosport-expert.png',
          short_description: 'Lorem Ipsum',
          long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          acquisition_cost: 285000,
          scrap_value: [10000, 20000],
          leasing_period: [12, 24],
          start_kilometer: 20000,
          end_kilometer: 35000,
          interval_kilometer: 5000,
          interval_price: 2500,
          model: 6,
          size: 3,
          colors: [1, 2],
          categories: [1],
          professions: [1, 2],
          equipments: [1, 2],
          economy: 25,
          gear: 'manual',
          energyLabel: 6,
          status: 'COMPLETED'
        },
        {
          o_variant: 'Titanium Petrol',
          variant: 'Titanium',
          year: '2018',
          primary_image: 'https://i.ibb.co/wcqGB07/ford-ecosport-titanium.png',
          thumbnail1: 'https://i.ibb.co/wcqGB07/ford-ecosport-titanium.png',
          thumbnail2: 'https://i.ibb.co/wcqGB07/ford-ecosport-titanium.png',
          thumbnail3: 'https://i.ibb.co/wcqGB07/ford-ecosport-titanium.png',
          thumbnail4: 'https://i.ibb.co/wcqGB07/ford-ecosport-titanium.png',
          short_description: 'Lorem Ipsum',
          long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          acquisition_cost: 285000,
          scrap_value: [20000, 40000],
          leasing_period: [24, 36],
          start_kilometer: 20000,
          end_kilometer: 35000,
          interval_kilometer: 5000,
          interval_price: 2500,
          model: 6,
          size: 3,
          colors: [1, 2],
          categories: [1],
          professions: [1, 2],
          equipments: [1, 2],
          economy: 30,
          gear: 'manual',
          energyLabel: 8,
          status: 'COMPLETED'
        },
        {
          o_variant: 'SE Smoke',
          variant: 'SE',
          year: '2019',
          primary_image: 'https://i.ibb.co/4fCmV5f/se-smoke.png',
          thumbnail1: 'https://i.ibb.co/4fCmV5f/se-smoke.png',
          thumbnail2: 'https://i.ibb.co/4fCmV5f/se-smoke.png',
          thumbnail3: 'https://i.ibb.co/4fCmV5f/se-smoke.png',
          thumbnail4: 'https://i.ibb.co/4fCmV5f/se-smoke.png',
          short_description: 'Lorem Ipsum',
          long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          acquisition_cost: 285000,
          scrap_value: [30000, 60000],
          leasing_period: [12, 36],
          start_kilometer: 10000,
          end_kilometer: 30000,
          interval_kilometer: 5000,
          interval_price: 2500,
          model: 6,
          size: 3,
          colors: [1, 2],
          categories: [1],
          professions: [1, 2],
          equipments: [1, 2],
          economy: 25,
          gear: 'manual',
          energyLabel: 5,
          status: 'COMPLETED'
        },
        {
          o_variant: 'San Antonio',
          variant: 'San Antonio',
          year: '2019',
          primary_image: 'https://i.ibb.co/0f3wKKp/sanantonia.png',
          thumbnail1: 'https://i.ibb.co/0f3wKKp/sanantonia.png',
          thumbnail2: 'https://i.ibb.co/0f3wKKp/sanantonia.png',
          thumbnail3: 'https://i.ibb.co/0f3wKKp/sanantonia.png',
          thumbnail4: 'https://i.ibb.co/0f3wKKp/sanantonia.png',
          short_description: 'Lorem Ipsum',
          long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          acquisition_cost: 285000,
          scrap_value: [10000, 20000],
          leasing_period: [12, 24],
          start_kilometer: 10000,
          end_kilometer: 25000,
          interval_kilometer: 3000,
          interval_price: 2500,
          model: 7,
          size: 1,
          colors: [1, 2],
          categories: [1],
          professions: [1, 2],
          equipments: [1, 2],
          economy: 25,
          gear: 'manual',
          energyLabel: 5,
          status: 'COMPLETED'
        },
        {
          o_variant: 'AB',
          variant: 'AB',
          year: '2019',
          primary_image: 'https://i.ibb.co/5hfHP5V/2019-volvo-xc40-onyx-black-metallic-032.png',
          thumbnail1: 'https://i.ibb.co/5hfHP5V/2019-volvo-xc40-onyx-black-metallic-032.png',
          thumbnail2: 'https://i.ibb.co/5hfHP5V/2019-volvo-xc40-onyx-black-metallic-032.png',
          thumbnail3: 'https://i.ibb.co/5hfHP5V/2019-volvo-xc40-onyx-black-metallic-032.png',
          thumbnail4: 'https://i.ibb.co/5hfHP5V/2019-volvo-xc40-onyx-black-metallic-032.png',
          short_description: 'Lorem Ipsum',
          long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          acquisition_cost: 285000,
          scrap_value: [10000, 20000],
          leasing_period: [12, 24],
          start_kilometer: 15000,
          end_kilometer: 30000,
          interval_kilometer: 5000,
          interval_price: 2500,
          model: 8,
          size: 1,
          colors: [1, 2],
          categories: [1],
          professions: [1, 2],
          equipments: [1, 2],
          economy: 25,
          gear: 'manual',
          energyLabel: 10,
          status: 'COMPLETED'
        },
        {
          o_variant: 'S Hatchback',
          variant: 'S',
          year: '2018',
          primary_image: 'https://i.ibb.co/wR5NpjM/wagen-product.png',
          thumbnail1: 'https://i.ibb.co/wR5NpjM/wagen-product.png',
          thumbnail2: 'https://i.ibb.co/wR5NpjM/wagen-product.png',
          thumbnail3: 'https://i.ibb.co/wR5NpjM/wagen-product.png',
          thumbnail4: 'https://i.ibb.co/wR5NpjM/wagen-product.png',
          short_description: 'Lorem Ipsum',
          long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          acquisition_cost: 200000,
          scrap_value: [20000, 30000],
          leasing_period: [12, 24],
          start_kilometer: 20000,
          end_kilometer: 40000,
          interval_kilometer: 4000,
          interval_price: 2500,
          model: 9,
          size: 2,
          colors: [1, 2],
          categories: [1],
          professions: [1, 2],
          equipments: [1, 2],
          economy: 35,
          gear: 'manual',
          energyLabel: 8,
          status: 'COMPLETED'
        }
      ]
      arrProduct.forEach(product => {
        db.Product.create(product, {
          include: [
            db.Model,
            db.Finance,
            db.Size
          ]
        })
          .then(prod => Promise.all([
            prod.setModel(product.model),
            prod.setSize(product.size),
            prod.setFinance(1),
            prod.setColors(product.colors),
            prod.setCategories(product.categories),
            prod.setEquipments(product.equipments),
            prod.setProfessions(product.professions)
          ]))
      })
    }
  })
}

module.exports = {
  run: run
}
