swagger: "2.0"
info:
  description: "Swagger Doc for Leasing Customer App"
  version: "0.0.1"
  title: "Leasing Customer Swagger Doc"
host: "localhost:3000"
basePath: "/api/v1"
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
